import sbt._
import Keys._

object Dependencies {

  val Scala211 = "2.11.12"
  val Scala213 = "2.13.0-M5"
  val ScalaVersions = Seq(Scala211)

  val AkkaVersion25 = "2.5.22"
  val AkkaVersion24 = "2.4.19"

  val AwsSdkVersion = "1.11.476"
  val AwsSdk2Version = "2.5.20"
  val AkkaHttpVersion = "10.1.7"
  val mockitoVersion = "2.27.0"

  val CouchbaseVersion = "2.7.2"              
  val CouchbaseVersionForDocs = "2.7"

  // Allows to silence scalac compilation warnings selectively by code block or file path
  // This is only compile time dependency, therefore it does not affect the generated bytecode
  // https://github.com/ghik/silencer
  val Silencer = {
    val Version = "1.3.1"
    Seq(
      compilerPlugin("com.github.ghik" %% "silencer-plugin" % Version),
      "com.github.ghik" %% "silencer-lib" % Version % Provided
    )
  }

  val Common = Seq(
    // These libraries are added to all modules via the `Common` AutoPlugin
    libraryDependencies ++= Seq(
      "com.typesafe.akka" %% "akka-stream" % AkkaVersion24,
      "com.typesafe.akka" %% "akka-stream-testkit" % AkkaVersion25 % Test, // Tests don't work against 24.
      "com.typesafe.akka" %% "akka-slf4j" % AkkaVersion25 % Test,
      "ch.qos.logback" % "logback-classic" % "1.2.3" % Test, // Eclipse Public License 1.0
      "org.scalatest" %% "scalatest" % "3.0.7" % Test, // ApacheV2
      "com.novocode" % "junit-interface" % "0.11" % Test, // BSD-style
      "junit" % "junit" % "4.12" % Test // Eclipse Public License 1.0
    )
  )

  val Csv = Seq(
    libraryDependencies ++= Seq()
  )

  val S3 = Seq(
    libraryDependencies ++= Seq(
      "com.typesafe.akka" %% "akka-http" % AkkaHttpVersion,
      "com.typesafe.akka" %% "akka-http-xml" % AkkaHttpVersion,
      "com.amazonaws" % "aws-java-sdk-core" % AwsSdkVersion, // ApacheV2
      // in-memory filesystem for file related tests
      "com.google.jimfs" % "jimfs" % "1.1" % Test, // ApacheV2
      "com.github.tomakehurst" % "wiremock" % "2.18.0" % Test // ApacheV2
    )
  )

}
